name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-pc-windows-gnu

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y mingw-w64

    - name: Build project
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: target/x86_64-pc-windows-gnu/release/rcat.exe
